name = "Controlz"
uuid = "e034abe6-471a-4d54-96dd-ecd1f4022419"
authors = ["SimonEnsemble <cory.simon@oregonstate.edu>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
